SELECT *
INTO OUTFILE '/tmp/Conductor.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM Conductor;

SELECT *
INTO OUTFILE '/tmp/Documento1.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM Documento;

SELECT *
INTO OUTFILE '/tmp/Flotilla.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM Flotilla;

SELECT *
INTO OUTFILE '/tmp/Mantenimiento1.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM Mantenimiento;

SELECT *
INTO OUTFILE '/tmp/Ruta1.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM Ruta;

SELECT *
INTO OUTFILE '/tmp/TransaccionCombustible.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM TransaccionCombustible;

SELECT *
INTO OUTFILE '/tmp/carro.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM Vehiculo;

