LOAD DATA INFILE '/tmp/carro.txt'
INTO TABLE Vehiculo
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

LOAD DATA INFILE '/tmp/Mantenimiento1.txt'
INTO TABLE Mantenimiento
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';